# @TECHNICAL TRAININGS@

## DATA PREPROCESSING

### Need of Data Preprocessing
• For achieving better results from the applied model in Machine Learning projects the format of the data has to be in a proper manner. Some specified Machine Learning model needs information in a specified format, for example, Random Forest algorithm does not support null values, therefore to execute random forest algorithm null values have to be managed from the original raw data set.

In [16]:
# Python code to Rescale data (between 0 and 1) 
import pandas 
import scipy 
import numpy 
from sklearn.preprocessing import MinMaxScaler 
dataframe = pandas.read_csv("iris.csv")

array = dataframe.values 

X = array[:,1:5]

scaler = MinMaxScaler(feature_range=(0, 1)) 
rescaledX = scaler.fit_transform(X) 

# summarize transformed data 
numpy.set_printoptions(precision=2) 
print(rescaledX[1:10,1:4]) 


[[0.42 0.07 0.04]
 [0.5  0.05 0.04]
 [0.46 0.08 0.04]
 [0.67 0.07 0.04]
 [0.79 0.12 0.12]
 [0.58 0.07 0.08]
 [0.58 0.08 0.04]
 [0.38 0.07 0.04]
 [0.46 0.08 0.  ]]


In [18]:
dataframe.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [19]:
# Python code for binarization 
from sklearn.preprocessing import Binarizer 
import pandas 
import numpy 
dataframe = pandas.read_csv("iris.csv")

array = dataframe.values 

# separate array into input and output components 
X = array[:,1:4] 
binarizer = Binarizer(threshold=3.2).fit(X) 
binaryX = binarizer.transform(X) 

# summarize transformed data 
numpy.set_printoptions(precision=3) 
print(binaryX[0:5,:]) 


[[1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]]


In [36]:
dataframe.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [20]:
# Python code to Standardize data (0 mean, 1 stdev) 
from sklearn.preprocessing import StandardScaler 
import pandas 
import numpy 
dataframe = pandas.read_csv("iris.csv")

array = dataframe.values 

# separate array into input and output components 
X = array[:,1:4] 
scaler = StandardScaler().fit(X) 
rescaledX = scaler.transform(X) 

# summarize transformed data 
numpy.set_printoptions(precision=3) 
print(rescaledX[0:5,:]) 


[[-0.901  1.032 -1.341]
 [-1.143 -0.125 -1.341]
 [-1.385  0.338 -1.398]
 [-1.507  0.106 -1.284]
 [-1.022  1.263 -1.341]]
